module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '💀', '🫀', '🧿', '👀', '🍁', '🚩', '🥰', '💓', '💜', '💙', '🔱', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/xveuc2.jpg',
    NEWSLETTER_JID: '@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝖐𝖎𝖓𝖌_𝚔𝚎𝚣𝚞_𝚖𝚒𝚗𝚒',
    OWNER_NAME: '𝗸𝗲𝘇𝘂_𝗯𝗼𝘇𝘇',
    OWNER_NUMBER: '94779885727',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝚔𝚎𝚣𝚞_𝚋𝚋𝚑',
    CHANNEL_LINK: 'https://whatsapp.com/channel/',
};
